version: "2"
services:
#define a service called app
  app:
    depends_on:
      - mongo
#adding a container name
    container_name: cruddockernmain
#restart the container automatically if it fails
    restart: always
#building the app image using the Dockerfile in the current directory
    build: .
#env
    environment:
      NODE_ENV: development
#mapping the host port to the container port.
    ports:
      - "4000:4000"
    links:
      - mongo
#create another service called mongo
  mongo:
    image: mongo:3.3
#mount the host directory for persistent storage
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
#creating a service called admin-mongo
  admin-mongo:
#pull down the official image from DockerHub registry
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    links:
      - mongo
volumes:
  mongo_data: